### PR TITLE
[CLOUD-390] Upgrade to kserve v0.10.0

### PR DESCRIPTION
**Pull request by gibchikafa**

### CODE REVIEW

**Comment by SirOibaf** [comment]
This is not a great way of maintaining the repository imho. With other OSS projects for which we maintain forks, we create a branch that matches the kserve/release-0.10 branch and then on top of it we apply our changes.

We don't try to merge the kserve/release-0.10 into master. Otherwise you end up with all sorts of conflicts.

**Comment by gibchikafa** [comment]
Alright. But in docker images we install from the master branch [https://github.com/logicalclocks/docker-images/blob/8227b07c63abe343c7ae5df0e3652a46e6827f64/base_image/python38/python_install.sh#L27](https://github.com/logicalclocks/docker-images/blob/8227b07c63abe343c7ae5df0e3652a46e6827f64/base_image/python38/python_install.sh#L27) so we need to start building from the branch.

**Comment by SirOibaf** [comment]
Yes - we should do it in such a way on Docker 3.1 images we build the old Kserve and in the 3.2 images we build 0.10 version

**Comment by gibchikafa** [comment]
Pushed one more commit on the docker images PR to build from kserve from the release branch https://github.com/logicalclocks/docker-images/pull/275/commits/2e2c909a042f48448818d0c5a32621e626f10ac9

**Pull request closed without merging**
